class Localization:
    survey_form = {
    	'en': {
	        'question_1_choices': (('0','Simulator'),
	               ('1','Adventure'),
	               ('2','Open world'),
	               ('3','Platform'),
	               ('4','Sports'),
	               ('5','Racing'),
	               ('6','Strategy'),
	               ('7','Shooter'),),
	        'question_3_choices': (('0','Yes'), ('1','No'), ('2',"I'm not sure"),)
	    },
	    'ru': {
	        'question_1_choices': (('0','Симуляторы'),
	               ('1','Приключенческие'),
	               ('2','Открытый мир'),
	               ('3','Платформеры'),
	               ('4','Спортивные'),
	               ('5','Гонки'),
	               ('6','Стратегии'),
	               ('7','Шутеры'),),
	        'question_3_choices': (('0','Да'), ('1','Нет'), ('2',"Я не уверен"),),
        },
        'all': {
        	'question_2_choices': (('1','1'), ('2','2'), ('3','3'), ('4','4'), ('5','5'), ('6','6'), ('7','7'), ('8','8'), ('9','9'), ('10','10'),),
        	'question_4_choices': (('0','<20'), ('1','21-30'), ('2','31-40'), ('3','41-50'), ('4','50+'),),
        	'question_6_choices': (('0', 'Windows'), ('1', 'Mac OS'), ('2', 'Linux'), ('3', 'PS4'),
        		('4', 'Xbox One'), ('5', 'iOS'), ('6', 'Android'))
        }
    }

    strings_en = {
        'survey_name': 'Survey',
        'survey_questions': ("1. What genres of computer games do you prefer?",
    	         "2. How important are computer games in your life? (on a scale of 1-10)",
    	         '3. Have you ever heard about the game "The Information Man"?',
    	         "4. What is your age?",
    	         "5. What story would you like to see in a computer game? (at least 256 characters)",
    	         "1. On what platforms do you prefer playing games?"),
        'submit_button': 'Submit',
        'index_header': 'Online-Survey for App',
        'index_welcome_message': 'Welcome to our website! Please, click the button in order to proceed to the survey',
        'survey_goto_message': ' Go to Survey',
        'thanks_message': 'Thank you for taking part in our survey! If you want to retake the survey, click the button in order to proceed to it',
        'survey_retake_message': ' Retake the Survey',
        'survey_results': 'Survey results',
        'survey_results_response': 'Response',
        'survey_results_graphs': 'Graphs',
        'survey_results_responses': 'Responses',
        'home_message': 'Home',
        'lang_switch_message': 'Русский 🇷🇺',
        'charts_question_1_yAxis': 'Answers',
        'charts_question_2_yAxis': 'Value',
        'charts_question_2_xAxis': 'Importance of games',
        'charts_valueSuffix': 'Answers',
        'charts_series_name': 'Survey',
        'login_headline' : 'Login',
        'logout_button' : 'Logout',
        'login_username' : 'username',
        'login_password' : 'password',
        'login_warning' : 'Warning!',
        'login_error' : 'Sorry, that login was invalid. Please try again.',
        'login_submit' : 'Login',
    }

    strings_ru = {
        'survey_name': 'Опрос',
        'survey_questions': ("1. Какие жанры компьютерных игр Вы предпочитаете?",
    	         "2. Насколько важны компьютерные игры в Вашей жизни? (оцените от 1 до 10)",
    	         '3. Слышали ли Вы когда-нибудь об игре "The Information Man"?',
    	         "4. Сколько Вам лет?",
    	         "5. Какой сюжет Вы хотели бы увидеть в компьютерной игре? (как минимум 256 символов)",
    	         "1. На каких платформах Вы играете в игры?"),
        'submit_button': 'Отправить',
        'index_header': 'Онлайн-опрос для приложения',
        'index_welcome_message': 'Добро пожаловать на наш сайт! Пожалуйста, нажми на кнопку, чтобы перейти к опросу',
        'survey_goto_message': ' Перейти к опросу',
        'thanks_message': 'Спасибо за прохождение нашего опроса! Нажмите на кнопку, если Вы хотите его перепройти.',
        'survey_retake_message': ' Перепройти опрос',
        'survey_results': 'Результаты опроса',
        'survey_results_response': 'Ответ',
        'survey_results_graphs': 'Графики',
        'survey_results_responses': 'Ответы',
        'home_message': 'Домой',
        'lang_switch_message': 'English 🇬🇧',
        'charts_question_1_yAxis': 'Ответы',
        'charts_question_2_yAxis': 'Значение',
        'charts_question_2_xAxis': 'Важность игр',
        'charts_valueSuffix': 'Ответы',
        'charts_series_name': 'Опрос',
        'login_headline' : 'Авторизация',
        'logout_button' : 'Выйти',
        'login_username' : 'имя пользователя',
        'login_password' : 'пароль',
        'login_warning' : 'Предупреждение!',
        'login_error' : 'Извините, неправильный логин или пароль. Попробуйте снова.',
        'login_submit' : 'Войти',
    }