class Localization:
    strings_en = {
        'survey_name': 'Survey',
        'survey_questions': ("1. What genres of computer games do you prefer?",
    	         "2. How important are computer games in your life? (on a scale of 1-10)",
    	         '3. Have you ever heard about the game "The Information Man"?',
    	         "4. What is your age?",
    	         "5. What story would you like to see in a computer game? (at least 256 characters)"),
        'submit_button': 'Submit',
        'index_header': 'Online-Survey for App',
        'index_welcome_message': 'Welcome to our website! Please, click the button in order to proceed to the survey',
        'survey_goto_message': ' Go to Survey',
        'thanks_message': 'Thank you for taking part in our survey! If you want to retake the survey, click the button in order to proceed to it',
        'survey_retake_message': ' Retake the Survey',
        'survey_results': 'Survey results',
        'survey_results_response': 'Response',
        'home_message': 'Home',
        'lang_switch_message': 'Русский 🇷🇺',
        'charts_question_1_yAxis': 'Answers',
        'charts_question_2_yAxis': 'Value',
        'charts_question_2_xAxis': 'Importance of games',
        'charts_valueSuffix': 'Answers',
        'login_headline' : 'Login',
        'logout_button' : 'Logout',
        'login_username' : 'username',
        'login_password' : 'password',
        'login_warning' : 'Warning!',
        'login_error' : 'Sorry, that login was invalid. Please try again.',
        'login_submit' : 'Login',
    }

    strings_ru = {
        'survey_name': 'Опрос',
        'survey_questions': ("1. Какие жанры компьютерных игр Вы предпочитаете?",
    	         "2. Насколько важны компьютерные игры в Вашей жизни? (оцените от 1 до 10)",
    	         '3. Слышали ли Вы когда-нибудь об игре "The Information Man"?',
    	         "4. Сколько Вам лет?",
    	         "5. Какой сюжет Вы хотели бы увидеть в компьютерной игре? (как минимум 256 символов)"),
        'submit_button': 'Отправить',
        'index_header': 'Онлайн-опрос для приложения',
        'index_welcome_message': 'Добро пожаловать на наш сайт! Пожалуйста, нажми на кнопку, чтобы перейти к опросу',
        'survey_goto_message': ' Перейти к опросу',
        'thanks_message': 'Спасибо за прохождение нашего опроса! Нажмите на кнопку, если Вы хотите его перепройти.',
        'survey_retake_message': ' Перепройти опрос',
        'survey_results': 'Результаты опроса',
        'survey_results_response': 'Ответ',
        'home_message': 'Домой',
        'lang_switch_message': 'English 🇬🇧',
        'charts_question_1_yAxis': 'Ответы',
        'charts_question_2_yAxis': 'Значение',
        'charts_question_2_xAxis': 'Важность игр',
        'charts_valueSuffix': 'Ответы',
        'login_headline' : 'Авторизация',
        'logout_button' : 'Выйти',
        'login_username' : 'имя пользователя',
        'login_password' : 'пароль',
        'login_warning' : 'Предупреждение!',
        'login_error' : 'Извините, неправильный логин или пароль. Попробуйте снова.',
        'login_submit' : 'Войти',
    }